# Generated by Django 4.2.11 on 2025-09-03 01:55

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(db_column='user_name', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=255, unique=True, verbose_name='email address')),
                ('phone_no', models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=100, null=True, unique=True, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='is Staff')),
                ('admin', models.BooleanField(db_column='is_admin', default=False, verbose_name='admin bool flag')),
                ('referrer_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='referrer_user')),
                ('is_remove', models.BooleanField(default=False, verbose_name='Remove')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'platform_user',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('expire', models.BooleanField(default=False, verbose_name='expire')),
                ('otp', models.IntegerField(blank=True, null=True, verbose_name='otp')),
                ('purpose', models.CharField(blank=True, choices=[('sign_up', 'Sign_up'), ('forget_password', 'Forget_password'), ('reset_password', 'Reset_password'), ('change_email', 'Change_email'), ('verify_account', 'Verify_account'), ('resend_otp', 'Resend_otp')], max_length=50, null=True, verbose_name='Purposes')),
                ('ttl', models.DateTimeField(blank=True, null=True, verbose_name='time to live')),
                ('is_remove', models.BooleanField(default=False, verbose_name='removed')),
                ('update', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'otp',
                'db_table': 'otp',
            },
        ),
    ]
