name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Django migrations and tests
        run: |
          ./backend/.venv/bin/python backend/manage.py migrate
          ./backend/.venv/bin/python backend/manage.py test

      - name: Build and push Docker image
        run: |
          docker build -t ahmedyasin1947/backend_web:latest ./backend
          docker push ahmedyasin1947/backend_web:latest
